version: '3.8'

services:
  app:
    container_name: bypolarmedia-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bypolarmedia?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - GITHUB_ID
      - GITHUB_SECRET
      - GOOGLE_ID
      - GOOGLE_SECRET
      - NEXTAUTH_SECRET
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - CLOUDINARY_URL
      - USER_FOLDER
    env_file:
      - .env
    command: sh -c "npx prisma@6.4.1 migrate deploy && node server.js"
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: bypolarmedia-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bypolarmedia
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:


networks:
  app-network:
    driver: bridge
